from __future__ import annotations

from backend.api.support.runtime_common import _get_tracker_change_event_repository
from backend.api.support.runtime_common import _get_tracker_repository
from backend.api.support.runtime_common import _not_found
from backend.api.support.runtime_common import _repository_error
from backend.api.support.runtime_common import _validation_error
from backend.api.support.tracker_support import _is_missing_tracker_change_events_table_error
from backend.api.support.tracker_support import _resolve_request_organization_id
from backend.api.support.tracker_support import _resolve_tracker_patch_actor
from backend.api.support.tracker_support import _to_audit_log_model
from backend.api.support.tracker_support import _to_tracker_change_event_model
from backend.api.support.tracker_support import _to_tracker_entry_model
from backend.api.support.tracker_support import _to_uuid_or_none
from backend.api.support.tracker_support import _validate_tracker_patch_request
